---
# tasks file for wordpress
- name: CentOS 6 | Redhat 6
  include: centos6-setup.yml
  when: ansible_distribution == "CentOS" and  ansible_distribution_major_version == '6'
- name: CentOS 7 | Redhat 7
  include: centos7-setup.yml
  when: (ansible_distribution == "CentOS"  and ansible_distribution_major_version > '6') or (ansible_distribution == "MostlyLinux"  and ansible_distribution_major_version > '6') or (ansible_distribution == "RedHat"  and ansible_distribution_major_version > '6')
- name: Ubuntu | Debian
  include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


