---
- name: Create mysql databases
  mysql_db: name="{{wp_db_name}}" state=present
- name: Create mariadb username and password
  mysql_user:
#    login_user=root
#    login_password=88888888 
    name="{{ wp_db_user }}"
    password="{{ wp_db_password }}"
    priv="*.*:ALL"

